
jwt:
  access_token_secret: oX5lRJjh2OE+50uhH3TiFmOs0DYf91N0xHlUxnqVdGg=--KzkaOHeeFEkPA4lIDo6YPA==
  refresh_token_secret: TsGB2DkgVokQWnbRYX9iYTs9m+xvKLtfLLze73fC3fY=--Dfb7//3Oeh64Zt/TDftCYw==

swagger:
  username: a+uR/wYL7SmL89h82aLnsK+tWLI1OX/GWrPR0g4So14=--beB/PNMHjvOYIxsqTdw/QQ==
  password: 43RbZFcoLXKlkTY/PwZB8YyD7hNRnPq06ucYZG9g9vg=--rrK9He6yxaU0Z3oT1vUtiQ==

database:
  name: koqdxsUb+d4vr24LzHxuKjjRomFpy5/dqysofZubSSA=--7C5HPxF9OJq2Dl5I8ZQkcw==
  host: IgDOuun6KYobkR4Wepm3Tw==--asOROISGc6tYYgas0Ljn2g==
  username: LYraMA+20wNeXJ4c9E56yQ==--bToEQ+fgaQlOsjiy6oF7oA==
  password: LRkC7p8Kq8VQQqvXWty3hg==--pz3mpU0PzB9Qh074qoP+mA==
  port: WK03tatnp53rPUPP9bTxCw==--tLT8U3AGTeSfkX+JaQAFlg==

emailLogin:
  tables: Z0D/YNrTAGVuoxJNPK5lbQ==--bXAQKHW5khxhfYqnLwgTAw==
  passwordMinLength: xESyTyt4nHL2MyYJptqkFg==--o2lh2xkXKlOFydvaCo3A/g==
  rememberFor: 0nQ3vkySPd1yfS5PaHTPLA==--tw+SZrIrnTVln69VK5sDgA==
  resetPasswordWithin: vWU78/kIrY6uRINwtGTPdQ==--MOAdhhw3fByF7qoZDtVWSg==
  maximumRetries: dBjNonTIxtassp/o4B48Cw==--fplBJuUHwNoalt119T7BLg==
  unlockIn: 2DF7CvTRa9kbxxoo0fDG3g==--gkgfGiNICVFZcQRoDunr6Q==
  passwordRegex: 7kQ8ydfZOf0Of9I2KKXbKH7EgaXVTAoLMCprarj0a8GJFpl4bwpnELlnWOtctyWSVqFmCd/FdViSUSc3RAqdWZLGTR+Etkvb6R+HXCSuUXY=--BrMX7heFfC1d/aKFB979uw==
  confirmationEmail: rMI9gxvePu9g1oPncKsQZA==--ou5RW/nuEgoDINF5P07Czg==


