
jwt:
  access_token_secret: V1uSa4xVYjNWbSGD9kbP0NvkiEDmVcSQk8F7iyHGJEA=--WlZRzEKsUKqS4218kYeQ1Q==
  refresh_token_secret: 1pGmQ08eqq17zbmkT1E/XrmlHT+iZddnHoJHKKRFDMw=--BbofFE9mt09jcvn8xxoBhw==

swagger:
  username: zPm/fB8b7u3HYKcdwL8tiwv9qLsfFi+lvfX0tpv/gFU=--AwEMrI30GjxhU17oeBTi/g==
  password: 00aHcAJzBwdXNeMskQfhJ7HRY6YO0tF1ZmYWlKDGbYQ=--rA6M+uV9elZKm+NZrpSBpQ==

database:
  name: N+dGJU3xm9GERE8v9XsTV5vHXT0WXheh/mSPgz0wCok=--npsc1K2/uS4zSdmibD1LYg==
  host: dwYFPDHwMG7u1pn20Mu4pA==--ekN61NmEbs5LKl/4zMj+tA==
  username: RABahQMbKuBZoW3YCr+6Ag==--RSQ2ro4jmTgwe0aGxUjeIw==
  password: mXbCS+KbXiy2tB44RUoJPw==--OVugoDyQr4LHrm6xX5ZHfQ==
  port: gpJ1TguyLur7REVbM3ZQKg==--BI8vYs8S6FH3MEYP9FClzA==

emailLogin:
  tables: SGGZNK55OpXnS64N8dRonA==--OAKp/BsvVUhTiohs7vZ9UQ==
  passwordMinLength: QW+UQUbptNIew7qbLTuStw==--WaPVohhY8xbgWyUd9cc7FA==
  rememberFor: vi2FOVW496kH70usOE84mA==--uZpuqOydWzC3Q/vRroJRJg==
  resetPasswordWithin: eGxeYJPABPTzMo5NbByxWQ==--FY0dEEorsT9gG4i3ZoDy/Q==
  maximumRetries: lBuKQJQOBIS8c4PuCokb3Q==--5M4zuJAE2XNwTjMMQmlK+A==
  unlockIn: Bw1PQdDT5ZqW57xWqcdpbA==--AVcjV3BBE5G29R/0HNmyWA==
  passwordRegex: cqLACOnxrxqNeb9Cbhkadihz1BOIQo20ORPkfG+XcfbT8WZ6Jm/XkFlQ8WnHDvKFFftcEDKeagXhzc4nNRHK3WmcAiRlxKpgPc4qlah46B8=--q49m5dZNOB5A7czi1ePOrg==
  confirmationEmail: vPgP7O8hVzvi6BGbl41ENA==--WzBf1MaxjxLBugP7DU9y8g==


