
jwt:
  access_token_secret: hguhik0XzWbW6plFzH790c5XEWCeiF9kmFjbC+xBjIg=--vFtBS7HSmElKsUPOtgARRQ==
  refresh_token_secret: lEyKJ4bEygIi2kMeikD2J3Vc3HmapD+1/lbMXgCFCwE=--7f8ATX6+dTP3Eodb4WRYzw==

swagger:
  username: n/M+bQEkjGD16E0xRJDm4aeN/fvNUuu8uNVVdl6nX5A=--ZKYct/AlyRll73W33fAFNQ==
  password: 3T2f9CJ92rEuq0s/KL3hdER5jD1yxzTspNjNZv81Zxs=--OiEAVJ3SWB55rDfesf+anw==

database:
  name: u52T1xyTU2+By8SmW3KkLJ9URdp50rizMrrWLRzhBOo=--RC3UOZwqTRD656nP4tyL8Q==
  host: 5+gQ9XhzeDFDuXswrHHcxg==--L45qX2926n1XMovTrkKWQg==
  username: xVbUptER8YbMbYkeFgNF7A==--yDkHFnMgxuQj/PsoHHs3HA==
  password: 0BPEkgcKRK6zi0ExX2uozg==--BtRKLQaLJRPPI7xr/xA3kQ==
  port: bPiZnZBHOvaMCJAvVD3Ezw==--tHz1sRx6JkPC+U5DL5AfkQ==

emailLogin:
  tables: 8uwAtNOE5vCs7OThwhkyGQ==--ZC1tw3QvVL7FDPivbzBuMg==
  passwordMinLength: HWtix/D43h87ZLyywbbLBA==--08pW9AQQ2YG/mwgICVT1gg==
  rememberFor: eNRityph20Rsg2R3OxlaPg==--HNmBw/xLivSt1HKKAkibpg==
  resetPasswordWithin: /tIPxGFRo8kDr0O0iSrM1g==--TZB6QzsXBQjrof7OURiasA==
  maximumRetries: Yly0rmtmHxyk827nY0eTbQ==--szZX7gpyc8Sn4o8WzAZ0xw==
  unlockIn: rhCst5kTs+nPHQ4dOlZBhw==--GI8P3DiWDGuMLEJ+WxxIwA==
  passwordRegex: moCPTAqUdINbxLN4h/T+U2YFJZXG2TPZq6Pb2Q2dk/nvtx/p3vqPU5MWDPyZg3H1NTE3ib/H/Zf701Y1FUllA61KKm0Yq88PCuxUqCOiffA=--HAkfB2BPp8lUfFpqJDS8Lg==
  confirmationEmail: mo3dfBPmWW/dBCDAApXuwA==--jv9d47jWaHz5UIcu+emrtA==


