
jwt:
  access_token_secret: Lvo74MHqNLRdximarLtvI4bZZGXWrCcKiaWVfCt1G2Y=--zgIxiGVVNKzIQ6La2I7Eaw==
  refresh_token_secret: C2OoCAujilyPEPNxaLReoEzl4qzoyufo8pfjVt6wyRQ=--n0abW9Ef+3gq8WOs0RwNvw==

swagger:
  username: OTUDd8WDjIf5CszVLS9tRiB3ANs4F3ndxgjRGWz/csk=--qnPSOmTGvqfW++3JTTUECg==
  password: bxsqfOEBIGS6Su+WqsaCL9CYq79YxMcioCSMsYAgoOU=--7okOw5YEyRMAB+QT0OY9sg==

database:
  name: /dWwyGHZrXluABnB9Yh9GT1UOqp547LseJnPUNhd1tc=--3cq4y/J986IICa9oVyds4Q==
  host: yXrnY7Sl1xsOCv7LA+rESQ==--DAvVb/UWPU+wPicMZ8Jcqw==
  username: OsBMkiDpEC+vKRwDrOKmMg==--pRilZia37TQpGZN1ilNkKw==
  password: 3YGJPW3+JS5qsn81eZ9kTA==--kVt6RUyFHdDcy7Rh6Hk7+g==
  port: aScOk2J2aP//cQh8iEst2w==--0FsnmCifBOHKtckCBQOm5Q==

emailLogin:
  tables: WDQipTwB1g+AywzQCZvoWw==--cD3tRvlwgfLGVHcKaDT7KQ==
  passwordMinLength: Rkmz2qmr0M5G5rxip4gSAA==--AJ6GWhS44VhGGTTxbhcJQw==
  rememberFor: GAw6dSbylYdh7IXT0gF37g==--IW1nQqHu1YgCE+j6LadZ7A==
  resetPasswordWithin: hdAjlnEljfQkQzJHzJGwmQ==--ZmwdYhgpdgT9IZcmjh65pw==
  maximumRetries: N1n8jOJMkPGkpHSm+T/Ndg==--dQNTOYFmE66rJUv+F1Pkrg==
  unlockIn: Xt2FWSKfTe+lOayFXvTkdw==--ubxZFqGKFNqbeq0U1BXd+g==
  passwordRegex: LLd8CrlW5lZIBA+LlyLYO7Gv663UDu/Y0nG8Tn+uFilN5OjN2VJgYZluQGv8YaAzyI7P1LJ3o6EasToeZ5+0yrScAI4RECQfoOscu2aXsoU=--J5h0b2H9D0L3v9AK3b70Pw==
  confirmationEmail: uLncQ6oYAU5lsIvgL8EUDA==--3Hup0Rqs4RBVTVSZ1bZCJA==


