
jwt:
  access_token_secret: bSk6uZVLSNEPM8xeFJCL2JNpGNhONG3yN7P33gNvsuQ=--6QTRcUji/9WP6Cyieu8weA==
  refresh_token_secret: 95iQexVEDe2pvLr7VHqutSxVIau9taUh2hSlOu8lTIY=--//mImY/97UhZyHDMPdZlVw==

swagger:
  username: H08v19lqp3acH7Ws0mthrnLC0UyQ4KKVyc1U4Rb9eKM=--W0zBVhSDAJKAfRbKHnaUoA==
  password: cHiGduPe9EWyEujMNVxT2fkWdeCZvTVCrz77HmGi1X0=--JzsrRsztXu6oe+OYuCw/Lw==

database:
  name: ViNgGij6fmOpDlQwnvdjfiktf+pphYYsH6JrpaWafxI=--iLcdSQlDP4tTXMemBKJMXg==
  host: GZqSGZFSFtNAjx/Rzetjxg==--iesV/sgH6eaNnIgT0+BIdA==
  username: jN8z26X8BTfMfNL2LbCPYA==--Sn/EMGSdVP1EkpMdyUHv4Q==
  password: 3b327BMaEzG/ZnFkZSSNQQ==--nyhRicSXYc7n7kV5X9MwAA==
  port: OwBovXFHbb20hClHYKzJzQ==--NB8rMCykwc3uWzMf/OSYwA==

emailLogin:
  tables: wFzcQccAoGPrcwjSNWUVKw==--0DUVw0/a2vucy37b8xyhKw==
  passwordMinLength: X0EAFSVtCEla9xGlnWJ5dA==--nU1+NTzMlRo+ggoNSvvxog==
  rememberFor: CHGQVRWsF4CmPqoHwyGBoQ==--H8O5GXttSRPWqBcJRllp5A==
  resetPasswordWithin: 8mbhifDOvO/orNAmPDls9w==--MQO/bB0Lz+MU9S/Poe/NHQ==
  maximumRetries: 8dBmD8PDTxI3GjpS2iRLSw==--9RoUvZu6YtYluDxm++X9jA==
  unlockIn: MpRAz0BEGDNhv6ZjmL6Ajw==--f4gymr/RaXO3sNY//eajMQ==
  passwordRegex: QNCnA72rv3xVEJzBFSqTLqKlkKsGmaQqr5MkJXQ8x2vtfrPwlWO0txAH+GJo3XAWqn8g3OojUl51Rr+ZOIRjxQjiFgkm1Lrgm6GfpYLgmsY=--MRxZp4vvjZl9T50SU8s41A==
  confirmationEmail: iYM+dea0BB/Pc+mnoVs+kw==--dlSrf/B8aCIpwVew71aqBQ==


