
jwt:
  access_token_secret: scnhQVevczO4bhcDRVFTvMP28AiEb3HhnQ7fdG2myLk=--HOTB3Iil1Fdwyb0vxOhSOg==
  refresh_token_secret: E5W0/XQaseNDt9TUggW/7/MvZEoCjk7YShS16jzI9/w=--lKAj+3AhMXfE8mdlt05VWQ==

swagger:
  username: yiGUtVhpGPytsrkt24fIE3E0CY7P4besfU0KfCW800Y=--MicXfojakt5KNU3GLvwuzw==
  password: OlV4s83RpMqDDtVbVjlcormhucYncmdZSH2iUulstBk=--GPqO5nat51Ae5EZd+UnrUw==

database:
  name: s1joBFUbJN8ocOuxanN5/Mm4WpYKumlSK7kZIfMqV+s=--A0UnY+5h6SEBi22sp4Qbqg==
  host: HU9DmGtT9QtX1zHipxI5LQ==--EcF9vxY5myvIcr6HKuaMJw==
  username: U94adbchxr9u4RD5ErXubA==--tJINuNfpzypsNiwKNuegYQ==
  password: ACLyYWWyDCJVCJFkVQXS3A==--dUnPHvjby8gkqlMmIOJ+rA==
  port: fCqzKcmdeT5Ly7R/Iql0wg==--CK55OBz0OWF9lZr/fQotEw==

emailLogin:
  tables: YX/umNoKtzfp4nEyrVCJ6w==--gFHmjhARdVGmhVDSH6q7ow==
  passwordMinLength: d8h8X17xVMdTD+K1z9q+HA==--fN6r3o3hzkl4mnzuc8Um4w==
  rememberFor: yQ87gpllhSrjWHfIVpquBQ==--rMInT9FmWy4XJyDy6NHFzw==
  resetPasswordWithin: MXJCRB+G2LQGXUAp6tuP2A==--+MDNx1g17WL+AqTYKpOu7g==
  maximumRetries: ingmjciEJ5EoNF0B4INnLA==--xMbVSsvDC9Xyn3SLJevqeQ==
  unlockIn: nEAjg8H3DiaLSzT2/hrmrg==--7q87Zlq+9/736kynBp57fA==
  passwordRegex: oQnjtMZJt3JTfrQwseDVf4eLr7Jz4zJDlnUa+kiahpUsSiMOyMx5cbwkCgW/PE7cSHxvig/tO/0zo3ZSWZaQA/jKm3GuOdvauLuug5ELH1U=--CPApI+P2lwwk9HYrFwAMEQ==
  confirmationEmail: jM4St0TOX+Cb1ORcADEtDQ==--1pmL/oe21BtwvFAHOtgyGg==


