
jwt:
  access_token_secret: mO3eHOXkHHBDwCcy6uPk8l4Gs22+g2BF7aSyMxJv1bk=--gyqLgvUu89sivjMttgk0Lw==
  refresh_token_secret: 5IoKSdnj5bi+BYyTObwzFBHx9Sp7gTksnYuwJezElf8=--thcfEQUPF0mxebOyQOXWtQ==

swagger:
  username: Iy0qum9ZnaI+cM92ptm2Bb8zgRBNMACdsAoml0lZwqc=--aMjZq9SlIO3wgbHKa/Mnlg==
  password: Sl6aKxs0/t4mrV2cXutwo8Ko/JtL87tH4owbYPuFIaE=--rjsptE+IHe+cVE85l5qhDw==

database:
  name: rhub2Xz5nkD5FVFg8sAqq+mG/Fg9a333IHASsSaxRiM=--HT2reodwhHHQDHrBH9q0mg==
  host: UPX3Tc0kIfj7l95CrJET/w==--8+padhBtnVj1SZbhD2t2pQ==
  username: AHZ/LsESYmCAn+dJg0EFew==--kUYSyjlllO4EaeecRBweTQ==
  password: PoRW1Ef1PN3EtN6sE0Ru3w==--QG+joH5oDPIHqh05VEVQVA==
  port: cOGYZ9aAQ+yqk5G/4Py8oA==--VNqtsKCOjqc1oE8JfWeQIQ==

emailLogin:
  tables: accWSVXY3HAXm99mThJs3w==--gq3KYnnrUBJnI4w7+sc4MQ==
  passwordMinLength: g30Q2JoFlHvMzsvjKyuohg==--iOQv9Y80VVAB+jy2usXCaQ==
  rememberFor: Qgvw3iIVKheZN04h2+48gw==--wMO4znCOS3eag4tV7KZplQ==
  resetPasswordWithin: jc1sl7I54onh7MZy5qnspw==--mxEsMBWBP+qs4lDFZjNsEg==
  maximumRetries: B1ULwrU+FAhTHcORE/IYCg==--3gbIHbKD+HDO3W7JU/iVHw==
  unlockIn: gNLz/Zb+WvNpUx1PtmglkQ==--Ys0ZMRSES2IZMc0vXefc3g==
  passwordRegex: 7DneI7WH74hksJEzaxVLCg25IeymS6y1UkhgcQsu7o3tERO5Sy6aiboXItKJ/XRLiM3k2KxrS1s1AmFSSKzoiMf0rDghJUps4whuvfeI7tM=--kBWAlmU1N/i/xG/h0DPXrA==
  confirmationEmail: HhwgL1KCEosdOPqgh5zgBw==--rc4BlJuUphRriCPjYQCySQ==


