
jwt:
  access_token_secret: shBu+7wZIOxoSIg05igTGODdCYWpspw1E306WSQjD50=--strMMG2BXnn1xfpQiQGMag==
  refresh_token_secret: A5ZT6xQDSHS87tOUwpGCtMKkzH4PKJIoPtXyeEtalqg=--ccCrNvgxNg31loCMOBqbjQ==

swagger:
  username: 5PhL//EiJIw0AnCEDS0x41jnH5QeLDrN/Fp/ygrK8C8=--wVvdvQejUexwglC+Tp6Vfg==
  password: FDDSCLFbEbGIM/S1/ZyO/pG9m2B67g5tPag8NUM12GA=--KUqvl8lJ/d2CLXJ8IAScUw==

database:
  name: EC438FQFXHUCL+EVJxGyLmiUMhqKCiyDvQJPqiyVzT8=--SMIrp6lh3XhDdV1vQrVYxQ==
  host: YgKShrmfFGMGmq1QR98Oug==--FJTyYFRKHt3d+B2ndOBwaw==
  username: mFo576sr15BcY37L/nht5g==--py+w+KgoVpw0tefYEtci2A==
  password: xQTABN3gz3B5wmN0hz2ZiQ==--N1eA9/hetSdNFVeb/SLTxA==
  port: YWJk+gryFHaAEmjx6ISDdA==--0clEO2pwAbA5cM3tra/l1w==

emailLogin:
  tables: OTOGjHc5Gh0B0FswOa8rgA==--1W8h7rOjNbNxkXxXnpUB9g==
  passwordMinLength: jwQUJeaAxNYUMnixdVEN8w==--r5dI4fG6RgkpIfZzZoJ2Fw==
  rememberFor: KKhbcpAiw+7thfpml5dRew==--EqEecv+D23oRDH4UcP4Uiw==
  resetPasswordWithin: FBOU2exDv5wBeh+WYr2jlw==--F+e2G3bocAU13Mn1OS0fvQ==
  maximumRetries: UUSF45VKccNNTdcpEaCv1Q==--7FvF27mo93z26G69uPFUdg==
  unlockIn: a4EuJ3QdaoVW2Is07GfW4Q==--IGjzNQrq/78RoK/Y5LBxSQ==
  passwordRegex: nb7K2K8flDlICaAttQzQ87x249/41keNMOxmpERJXwqzQLI97Fjurki0U3OmvwVCv9L8PiE3h/lh+j2wQWyWk0JxTXaVEb6c//vlP9mxEWs=--vp5wIaJJ+mcVa8nmmcQIxw==
  confirmationEmail: UmUwTW3pmDTj9U72Xe5VwA==--3B9P6Fyzu3Sdy7DwcOfIpw==


