
jwt:
  access_token_secret: yJPjR8CXO7+WUv9swzkcJVCcTap1fvGbHgL3AASnt0A=--MqB6TlqDwgWXqaw6hDzmZA==
  refresh_token_secret: k51PJeTzqDyQNV/ENDW3KuRAIK65QRwnZVQVyNwIRFw=--9kXCqqx5Az5cPKW27jNqaw==

swagger:
  username: u2rR9etJcPbhW61FAAJ9xvVQqIzK9JRmRKCY4+R7j4M=--MnPv9toli0JuQwmq9C9Jzw==
  password: Ocz/mdF8uDIMnEXvOfp/Wtf2Bwuy7TRYDClRQXQFhcU=--inVAJblyS/RObF9Qhtomdw==

database:
  name: qNj/eisr9Q6Uwb+gn2f16bXty8TqO8QiT4NVsZJm1U0=--95TbAmPWAYf9QZj0UKCyfQ==
  host: yRlo6y0l+DulL4RrpPYG9w==--+9HA4bThwMq4CVQo4LgRjw==
  username: /W0z8S3677eZAOr0cjeasA==--4Mwumd8o17kDrZisREy3XA==
  password: P6LbwZCviI0OJhysdxgqwg==--myn0r80MQ3+qjx5CoLqdpA==
  port: FJWHfOv7/b4yRiPae1pITw==--jHdPSA6KUfhfCJh5eRXBHQ==

emailLogin:
  tables: gzbmiYATcalJAm4loAxDDQ==--Anoc5OKUrtkF1TeUsM0bgA==
  passwordMinLength: gNoXJJW1ZZt4jcDJEwV+vQ==--+xngEF+KkyOzyS1Sq0IKDg==
  rememberFor: oSjo6ivnOWrlya/v7R0iaQ==--VOqPvgau840+i++D+v50ZA==
  resetPasswordWithin: AAm4gUoq4VXIn0lC9HIlMA==--v8vnCSw4RVQZpBeWVdD+EQ==
  maximumRetries: CfECRYhwQg9qcUDh/ZN4+Q==--eVCJuF/vQa1md8KrLasIgQ==
  unlockIn: CP14vs8a51NoruvnzgN8KA==--MWb432rdJ9K+iXte6HV7+A==
  passwordRegex: p88YMMA9ZA5Sp9W7oL+8AjgNWFkERh3S9deJJ7Ebu2ObX7Esd1eM0erCNNbjVyso59t0CRQlSrASTteMyqg+UmoijX/bGTV5uc8Gq6oWNgA=--+2AJOqq9RcA4JqydbbAROA==
  confirmationEmail: sIZNRvYiDE97JwqTZIhJNg==--J3QJKcO7Df0btnkanD5IgA==


