
jwt:
  access_token_secret: mYXYC4J/Rho+8Wog8kwMrB36gQagmVJm1bHIkMhYnmo=--fU8Ue7tQ+lGHr+JV1VhNGQ==
  refresh_token_secret: PAqDPRsitbTZyLXZ2mhWJ58vXnrMe6un+xxY5D8JKt4=--/bhXFRcgcsdthsu2AwxFvQ==

swagger:
  username: TuXD9o0kJ2Z/SwDBnLAK7jIfSxOH3dwjHTQdr3ErhfA=--zuI5pAt+GYpCPt2PnSdDcg==
  password: DuA9f6vhs9LB7omeAursh5bP0oxHhk+6rc7di0ZCoOc=--DXWd7j8t5uigkEN6g6YVNg==

database:
  name: B1zyCZ7a0u+JBxU7yaC9BrqqpIgcP8+phvdtJrIDESo=--xjktkesHdgQtxSR5VLk6bQ==
  host: /bt2ElyV03ci+g5//XDMJQ==--1WfojXsfHwMsF9ja6KYmXA==
  username: WHId7GXxKBhSRRBdEn0IVg==--fd/RFIY0feb2iypujJZoRQ==
  password: uxedRWxVHRXBXngbOaOLAQ==--26G91BXEKGZ+ySi+zaumGw==
  port: SUG93854XDtMcVlCWJzp/g==--Hz2+/sJ3irmnCbkS2oidmw==

emailLogin:
  tables: vdRCZAforg5nwDLyawiz0Q==--uFizqLF10JsoWYcyoeqOpQ==
  passwordMinLength: TuHT7l+kd0nVhGGTYC+NRA==--Y+pz9RdV9KP4J57AQMf9Kw==
  rememberFor: w0LqrqZ55RJyri79hcGt9w==--D5tdL0v8ryuWH1xzj7EkXA==
  resetPasswordWithin: anafeCdxVv8htV9rDg2N/Q==--dnwDsKb2YVANIDET/85iZA==
  maximumRetries: EeSVYNITxG7kiCKs9gvQ/A==--O7tDhwa2nQdsc63FEnzg6g==
  unlockIn: bU82VXnlTFf5sUsuyejM8Q==--KBnHwKui7E99w8TdOa1C5A==
  passwordRegex: iG7FeaDZ8vpXhRr5OWRFgnTT9KI5ZImLLvp6zvihiB9rtPUS6tyhujUA6n43zrXXQjvgllwTRg2rcTukiyN/RcaEzHGFWNWS2NUgnw6NcbM=--4kO5kJIpKUtDGbmoMyeyTA==
  confirmationEmail: a42D/0zdZH4s1c6/D2HtmA==--SaOXkQHWl8LA6Ia8iQcXTQ==


