
jwt:
  access_token_secret: QaapXiJ/k1ssN/cHIMNZKvHu1E5vGJIUhH59dhdgwd4=--/xPCSBo8j/azv6UsX/j0zQ==
  refresh_token_secret: 5zfzld2VLqewDRqh/bjIYfNW3xOg7UgGvmD5YLhaWSs=--11oiCChYhd0/GgdWQxWwIg==

swagger:
  username: BgEVttwU7mbMWGxCab650k2ASEJKKVI0iZQJeD3/kAY=--kA7HfBhNYEQryEVSoZgS2Q==
  password: OSrIQcFEm3ny8Bm6F9gdftvugA0pMzZJqlSgRSpXsAY=--VZAkj9LlX5EZGucPIjpsOg==

database:
  name: AzhZ9fmM7dQW9PsuhGAEPvmcpnt2qFvehyRtpE4FKzc=--UQ34zfGO2L9SNv+ncVEuOw==
  host: 8bhBPskZDsqDQ87Io04mkw==--C0tYxVe0/XaR6LfSgickSA==
  username: omuGu7RPJtp1huag7+CL2A==--fsWxV1y1iKSOAehabA4E/Q==
  password: yk1uTG177YTwBfnJuOOLaQ==--itkLiuw0hy3vXo1DkqXbXA==
  port: Tuy8xNHg1uFt23lRuHL7RQ==--CTd2tVGf86bA+3vgPnFP/w==

emailLogin:
  tables: vyhl/WsrypBup9HS6yJy5g==--Ks7S0ZZ0QcR4vUj6CedH4A==
  passwordMinLength: cWCFhIpkwCafn+I6cL8Vag==--G+7dlaXAmqbvWAPsKrmxJw==
  rememberFor: 5SfQJc2WhbHxEym8Dd3/Dg==--1UG5AlKjtz4iU6QaS9cFWw==
  resetPasswordWithin: 0ScRDhGNm86Rq8QJYQP/Qg==--4zPu87DXPoB67jaR97Nrkg==
  maximumRetries: Pzh6gN5h8TOLG/XWY5tF8g==--UhWzg5xGeUD+lfFn+dljjw==
  unlockIn: 1XSNqP3Qd6CI8N9OItfPDg==--GakZPcLQVfhH7UAUN3vEiw==
  passwordRegex: mAsNk3XSgkh2K3uflKOu8gIY59W27sZ2tLSJ/3MS39Ru2kvHGhErzZFZrCcdrpVmNgX5FDQhQE11mMt9hVNNZrG71kFSvdyuNsaLBR0k9/o=--X39dt/Fj7oZ604GrQbrlEA==
  confirmationEmail: l4cf202VPhygwggYNbmjvw==--4SJQtpda/PN52FMoDwEJ1A==


