
jwt:
  access_token_secret: s9o/QXypnq+mBzJMs0Nkfd8p/kKVnrRsFBaLwdU2KIs=--b7UeLEVQEYH2so7asfeMUA==
  refresh_token_secret: NwXTnXQuBh0QHEn9NHHyEsvjY4yxtA1jqd02uswbozw=--3SMCTjjuHl6hy5bGn9M+bg==

swagger:
  username: aRgOLnGC+cH5FHfufpxLHjZCAJB/Ul6IWlwRlFTnlrc=--QiYlWtFYu0aEkGOXqCCbYA==
  password: rkfXqa9VgOglYZKkUv/71boGNRbkVJMe9nEVNyPIylE=--clg6XGrliWUFd4cG/j23Og==

database:
  name: 5OZ8Bon9C4TqDN8wa8CuNN8TacUCJhrFszFrdCsA3eg=--c7kQjFHL0uqYQYjWBLlKeQ==
  host: Xd7dXggkEK0lFkjryqEJSA==--yWzR37UrXgBkggk1kq5FHA==
  username: BL+UzGRwNGSdKKSAZBcycw==--UwJsGtFQS2fNSJDX2vRgfg==
  password: nSpw3jsTp3SkR++hQ7UR6A==--9QW8s7JGce3tLy/crnYUeQ==
  port: XMe2GQFU32S3JUXOF8edCQ==--ESS7TUvWk5/w/+AxhIB6Uw==

emailLogin:
  tables: SDQMIVlUyVetwAmCKahPnA==--+NtSR96X2wFbUZd2HOQiBQ==
  passwordMinLength: usdp7YILCxQDdHiGDWRdRg==--vIqSSucLVJ1mMmrM3121jg==
  rememberFor: rQvp05q87FUDzefpPXinNQ==--PC2TWI9WMPQYKpRvAqaMcA==
  resetPasswordWithin: /lIKfOYmErSwP44Lsi8nGA==--WSj+8alzBWFK4GYZ2fz5jA==
  maximumRetries: r9xok1bUgPYZZ6e/i5eabA==--30ppdHT04numQI1NvMk9sg==
  unlockIn: 2MB+ozv8MgKbVGjev1gfOw==--dEKGFz2gRcZXav4ELUvEMA==
  passwordRegex: nvDWlFOxwHRQi4Lm6p/g9lyLc+frEVrL3l/mwBLz70nniTYf9Trs58inFMqOwhj6oqDhJOcC7W9b1CvFc6fm5Ohb0xsdezd37CaRvcBudxg=--UxNvCtYgmkwSPIKTRnocLA==
  confirmationEmail: BJ6+Lk/e2WMJfYtv+dGlsg==--7N2gb7ZdhVa1gt6jxeYMdg==


