
jwt:
  access_token_secret: ptCNgbPS9BhJEFbkMCXXeaCmZJwqAiBGfsLNtXfVxm8=--bsnAW/IReHAxAe75MAjg8w==
  refresh_token_secret: B43S++a1Nxi9Jnrk5bwUPyCFxE/b0YRdXzFGHuJHLMQ=--ksv7Fa0Y6cBIzcuhWMolWw==

swagger:
  username: d9E21B05S6FywKCUmHpduSbcOJHCAFb5OEAoyek2Vz4=--qtsGlmuWF7Rao6rwCdsuVg==
  password: ssaIZAuHjloLZA/0pbBUT1XzUCiNDxlEP03T6nUcZ2o=--fOhCuzIBGVKTL1hRyAOSHg==

database:
  name: Ki4qElXqd1cRCyX2jHc1u11scEzqcb/wV91IDp+uBSs=--MhE3tG50bWC7P3/jX5CMEA==
  host: jph+zZxCmsz+LEjCJbBthA==--Lgv+QIs3qGyAhl9uWp7SQw==
  username: DXZVqV+p3L+onlgXaUdPgQ==--r1Cg/jA7VG6IjZf9GijVnQ==
  password: LrB9Cs0R/Vv+nYHk7ss5HA==--0M4dGZb4sMx2PzSUkK0A9w==
  port: pB1dorhx579Iyv7PjaYFTw==--9BZZSW3QWEKM9hj9zbYKUA==

emailLogin:
  tables: IOlxu+Czq9lCwrpTXa41MQ==--CFm7kyJfj8684kDYbzGHGA==
  passwordMinLength: NaLrLdKmmU/Z+ZFHHRAS9g==--LJ6l6q5R3Mw2s51z7lB3iA==
  rememberFor: 4ry0IH8P2Y5HavcSoU6PVQ==--e8rMpyGUlee27yGkoJnIwQ==
  resetPasswordWithin: 1F4M3+V0UH7/iulQ2K3ZjA==--PwpwtpKpDc/x6VmdelUQwg==
  maximumRetries: Z+1M5CnExrHeoivgfhA+HA==--tcilMS0qF3dXAVUWYYXs6A==
  unlockIn: KpNcdvaQz+qOLk5bIsy38Q==--plRZspibkR+ZF0bxn85QmQ==
  passwordRegex: psYs/sLNMi+KBFsFE1wa48V/gseW0lyQntsCR1JKbiP9WB8SgIR64PSqpVpoGFahnhsPxwL84O2WQXFCuiAHPlNl2R7tRXOk73bbjtcuD04=--u5+LDnR4nq57C4Ni0J/LpQ==
  confirmationEmail: YToVrdOQBdfKyR0h2g8XDQ==--Muq9p31CVwwUbP0y8BjFNQ==


