
jwt:
  access_token_secret: zaEc39PO2qV+5r4aj00akeQ7ICLzlOXCrHU/5ErkVkM=--J/e52/yqRM69Vcjxt0lugw==
  refresh_token_secret: BHff/93Q5+/mp8grA0u4SmcnTHBeWR0avELMKVJRAGc=--G6PE/sDGAGvzY9hwELFGTA==

swagger:
  username: iNI4RRCYJoUeVBq1XBreMpIYQFCSLb2Egw9yvnmtgRU=--0Lr1HjHBsy2QrDUUchQa6A==
  password: cRKDiPOxNIAZQCINk0yctJvUPahVvB6XP1K9OOvWH38=--Dwv/kX8NZIxWnsO1d1gxVg==

database:
  name: stRXktrtKJ1a4lzv4bNCxR2Gir5taPSjiV22Oc1GSNc=--KBE7MPJ+RnzAqYEkyorkfQ==
  host: ciR+7SZ5/m27yrs+U58WTQ==--Z0J/55ekUzKmQaoa2f/BzQ==
  username: oVQ2zhbZqIyWd+gGlbPrGA==--BBgTBKvzplYRbcEQlaFyeg==
  password: t2i8Dm1Gt8Cqr3wVJCR0Bw==--WTDGzzvVb5kkzDWNx6dCpQ==
  port: 2Sh+2bu2mKxmN6Cj6/y38Q==--oejlVg3AC6uC4Ook+f3ndQ==

emailLogin:
  tables: EZHt+E08x25nI1h3QrSjjg==--uHrJw6ZeK99Mrc5NyoqlQQ==
  passwordMinLength: iuujr182sZ83ooJZ1IIXsg==--ydrHdsk5Y2tdzf6whNJFIA==
  rememberFor: IQLFsiFUbHCqM9h8uASO+A==--9GJaUe97x9HNwlW26OpZPQ==
  resetPasswordWithin: GyiG/bnhidqkzo5QcjOPMA==--SoHP0HJOFHLm60/VEQeCvQ==
  maximumRetries: 1B7Wub4WTxkX8unkgJX8LQ==--62sLJIRfvKNNPMcrocz9xA==
  unlockIn: p0NlAyChpBwEKGwLgOd3LA==--WriCHsTsNTrO4oaSebN7uw==
  passwordRegex: Q6pKyK2UKJVzKXyepjE2nQNXXvZVZW5M6Xsc3V4a46IIcH/GhAmDl+zw0zoYAVymwI3jYmLShLtFlmIvLB653gDy+9si0RjvyeNUXKOKDlU=--k+PGU+x4NmSReMcwt3k+MQ==
  confirmationEmail: 4mPtkddxgYj4CIHzbwzLig==--NKHE4llQzy/rbaoCNN0AaA==


