
jwt:
  access_token_secret: MxyS0ZOH8usgSaNhb8uvLzIca9x+lytBZeI1mkrt7Og=--P4EhlC1bSJ8JBRrG6HhnbQ==
  refresh_token_secret: tF7FQlqTQFZ8jbVOwH2bNs6UECuVGW9rID2JnGX/PpU=--Z/GCdiJZUI76xt70ftBOQg==

swagger:
  username: d11LCdL4Nyu02JfKrDDbU7xVu1M2kUkbt60fj5Muz1Q=--OeQr17HlixTVHYxhwl7sPQ==
  password: 2fmTgIZ6k+QX0KB+tUTGH103GBb163EiPpj5rD6O7xk=--tAa8CAFUcq10d3sp2N2Q7w==

database:
  name: zzRMnQO+IFBh8u7fHRYXkBZk0P2qHC9vbU6bs9eBhLM=--vC3NZCMIumJzenryGWotNA==
  host: i8FmVyWTSpOAcnbsH59v8Q==--1CPn7jRkez+K5KvBfr5iUA==
  username: krM2EMUh8VbVCrde9QeCWg==--jUCRyBOF90KuYuV1vWsKOw==
  password: y8QrrgiM4dG8DMni6ux27w==--p+H8JxhZC/JWhD8gApElrw==
  port: 0rY596ZyJsklS+SOYEu3uw==--L9t7Fb78yd1tSOeRmWdaPQ==

emailLogin:
  tables: X4jiCE6Wf2CgZztCyi9j6A==--SKOUcpdUnd9Y68BPV2Z73w==
  passwordMinLength: iIUyUXpb5Vmsloo3SwqrwQ==--O51CJqDsS3Q0DMJMZc4Q+Q==
  rememberFor: /tPWcZPjES7Tn1+yBze97w==--fXPK39r83+fNtD1euA37ZA==
  resetPasswordWithin: 9SzvmdpKPgIfNfDCDS/SRQ==--PhJScicHmWau6vU/oroLLQ==
  maximumRetries: zuIkQxExH1Nn+uJglXuBVQ==--YBVTTsYiifJ1FareILHITA==
  unlockIn: Lsw0vHaT6WnBpEW0nOaENg==--mRMA7u+VxFifjXG2EH+liQ==
  passwordRegex: N1omFjzKSoKIe9hcN2yh5/RUaFqwzuAq/ZH6ptNkwR+EonWXii3u1naLoeMAVNtOUVrOTHVIXa+M2dSHF7v8UWz6bEb0DqT84jyAgZfHH8M=--O0B2x1NXceaaNaMTPTWdhg==
  confirmationEmail: 25nqCyKs3PKLQt3tAw3k8w==--4lnMtgopc/WS7Z1m9jCSjA==


