
jwt:
  access_token_secret: 8s1PTC738N22xRWWxmbzXGeQ9i0UWQx1b10ad3zKDfY=--38FSKXCgPqCjTRcj9U9LMg==
  refresh_token_secret: odRTxJ1a/5ynGdaJqSeQM1MpSJFa5gWkq8mMjPuLZr8=--s96jFmGPnLZMwbzbr+B7Cw==

swagger:
  username: lklWZkv2NKbaVhIIljDpQXTDbHKGsPa4SWjHWWBl1FA=--rZQ2BbQwpqf0kUQz6WBnHw==
  password: hIN/6WyC1FfJSvA5Is2Yeb3Yh41MYdNekQUuM8tm4jM=--3UWgPjNaZMcXWJuChTyWhA==

database:
  name: FEbZFHFOzbT/6XongE4lvflrAiacHE0RjHaNChG6dhQ=--U6dWxhD+WdXc4xHIF2yAQQ==
  host: LBqyvHX8Tk6+OHUx0LkzSA==--beHTUjbl7gdkcsf+UR96UA==
  username: jJQgn3n149xrnkO1cnAyoQ==--SsgYa2I8rgnfDgdOF07DhQ==
  password: rlZJqlWxbVFVFeMy4HQMjw==--uBzSyrQlRALi3o4GvmUmpw==
  port: VkHW95HgqViEwb3DTb1LmA==--aYhP4w51zoGnvhLb3E2aLw==

emailLogin:
  tables: u9JKNKy2TuJfHxJMAH2CJQ==--Y8/qaV9PdhHJqfn86XibzA==
  passwordMinLength: iQ1dstpwO6YWOR2275p9ew==--0VgeaeNjnyMUpPwQW2uZGQ==
  rememberFor: bGRD4M+647gHpCfjhmxldQ==--l296smFlZ/bYsXF8ipv+yw==
  resetPasswordWithin: hpHfixzjiQKAeR2hhLBvEA==--AONMW20zddpdr4GOA/4U0g==
  maximumRetries: CRA+dPdHU17yzABqE1x+DA==--uj/vZjcmgSOVRRM+V9hC6A==
  unlockIn: YwQVplKENmsAeb/yVZqZIg==--3fXinhPEP5dFiszhTrPYBw==
  passwordRegex: eGLBjrJlhVXYPToZ6LD3ljIa1l89FbSjSVq3g4nDC4QxmHnfaVrkeWwl5e9XynNxuXGXVCd68AUfdQKHpbznX5dcgSwClS2dtZ6rPEtzDYc=--6JU5ILE1mL1Rz6RcwFTAcg==
  confirmationEmail: XhHfFn/Z7CnSs0dWHj56sw==--cfmKMpcTs7rlbjR6UzjUIw==


