
jwt:
  access_token_secret: RIWOcWX9/cQZiXpyZzoE27MrOcxnH8THBKaLtbu6fzU=--RwZyl7XSlDSZm3yoGcmOFw==
  refresh_token_secret: 0AmwZPS4pO1jhMsP5Nfq9iYZHWL+xZhdRjIPzkWKGgc=--1vIm4Ul/OFD1sRxjX33SNQ==

swagger:
  username: h150LD2UEfYD8xOq2DpARB6YTm+6F99ThRmSD46shUU=--AIEUD1+z39NrKAHn0RLyqw==
  password: SP7NJvtIt+t+gN5qOQU61kExZqLgx66p47w/Kkwufc0=--NUWGBfuJ2IoL2t/sJ4UAsA==

database:
  name: dtLg81gJGInD58uNvIiF0CLIa+l2Vrw2sXTsfhF23ZQ=--lFCDiacHt5DpotRRyoAdNQ==
  host: WLsMsohdr62QXkTnD2B7VQ==--N0jnpyZ5GSpgodsbPFwAjA==
  username: 0mrpwCwmoAIpN2lsjUG6yw==--uZnWNyMooBBguBFnYXqsaQ==
  password: YwnIffBVfyqQIOh7nSGdsg==--l5mUY2FAwWTSySGZOn6xGQ==
  port: VcIbgZCb/3FSdMdDYwDyOA==--pDEY/DkzX5eol3JO/f2Yzg==

emailLogin:
  tables: 13YUV0yyAO8vXyH1m4sBJQ==--YHTqrutMoIPh4jHOKLR0VQ==
  passwordMinLength: mm0LOVNbAPqszwy+bf+vKQ==--J98C6lv+vS+ldap0kValPw==
  rememberFor: nVCT7SbPBzQbDP66fYAHFQ==--zSb9ciyALSrlm5hCO+Lx4Q==
  resetPasswordWithin: +H8enWc3PQVBL9kMSwD5qQ==--VKMx6UxLxU6lHB/XcxRoxQ==
  maximumRetries: 0ZQHC06d4dLSQoixmcx59Q==--pM7aYS7uK4D99sOPJVBTWw==
  unlockIn: XqSFxk7H5FsNjKp+Clxw/A==--VJMUh9FvhSegJXRqUGNVIw==
  passwordRegex: EQC9HV2lXzRdhR3eX+lnERmuTp70j/KrNDwqaMZQXAcnDMFIzUoWqpqGj6Z0GAxAl9Spvh8UCzR2Ni2xLe2PStZzHYhD7q1in55SghbQE0k=--s06yupFoFvqS2cip9W+u5A==
  confirmationEmail: 0FClKNoA/4YuvotGz3XSHg==--0+WHOAbjoUB4MokZg/LbkQ==


