
jwt:
  access_token_secret: 6eTeTSFPIWknBRU/HEz1nP3o43nI5wlFEpH57bXNWqA=--WuXBgW32j41HwQGYxweC6A==
  refresh_token_secret: pQlOs5awyGaQxjNsBf9O8vbHF1NeP71XPKBiE5ZOq1Y=--YVbkAGriJdJIPlPZoKhKRw==

swagger:
  username: rqx7yzG4fEfu5KhZLRCKeJ9lVfYfD/JXSf5IiMMoe/s=--sRkaTFBQbNq0eAE9/6VLkw==
  password: YQX9shJ4ZE98BqL9NWB7hTLRnlFzuNBIqJhyJfNdBJ0=--nz7ewEmtz0+f+TzGXk+o1g==

database:
  name: 50Lvw3YA6nqu9ZLp/Yq3M/yVTT4vHqZJgqWsSVNOW7Y=--0+grDwEWPnxobAukCBlC6Q==
  host: nXx0gDHHcnBvPOOtA6iWvA==--SMVo7jRJCJoFIl63PlnB0w==
  username: n49mdVTJ3ghK4x52WIzO+g==--D3JIr2q/EkOk6aCFdBbBXw==
  password: 4w1mXXie7jFdTQ1lwE6MoA==--YwmX5aobGpzS/j6A8z0+Zw==
  port: Q2wSzPt1mAeZGrpuDNxsgQ==--f2jqMM/G7mAIRAR0mUpuDw==

emailLogin:
  tables: 7f/Fv33kc/VSTtS+/QSB2g==--o0NHJ9pGxLF/u1B2V/bdVg==
  passwordMinLength: xCDLiNXsseflugFCKw2Vxg==--/UaSPlpxqqcXScaLwsCzPQ==
  rememberFor: k+Zz6ioqLgaUTgYAeuBgBQ==--kew1uVq1oJ3Q7bkQZVnIzw==
  resetPasswordWithin: wGKaoEJ+SwGgt6PDnXH67A==--9YsaBWzyTKkaol2jryt1gg==
  maximumRetries: 6YurwPHrsdBQG2/YApo6TQ==--VbnLWwqcQbe8sKFeSUy6AA==
  unlockIn: PZeaWa0R6HSgy/HqfQQgqA==--W8leZuVJnoFnfyeHi/JjTg==
  passwordRegex: T9Tki/IQ7lrah6CG99j91BwEk4rOKMjOlo+yHwUfz/ioPGAmRcvNy0RhwYa5bUVz0I1iUpjAnGsdwiq5dPr/fgfwlAojDJqbmYgXpkqMsr4=--SSyLydIZgzGwxzUag/Q1Zg==
  confirmationEmail: 0jcTRHxhZhwmZBY/tK1vJQ==--Knv3cekNdeDrBVUUYhnnzQ==


