
jwt:
  access_token_secret: R8YdP5af+U2h0R4Hda7DInGotZGXOZZTFSglmzpQOms=--OxHdSF9HfBw3IXMKu1e4pQ==
  refresh_token_secret: raBsy+NS71s8Z7ac8054a0gebZQnhhN92Pg4uzvWQJg=--P4OV3og5CysF7J57QqVc4g==

swagger:
  username: D34jW8OLFtKdgvNGdaXmVLz25PN+/pK427IVQ00zyV8=--tXTVinZDz+Kqkv35PdxMQw==
  password: mkYOgNwQyGuTu5AVlHq/TDt/wy5y3CS/gAy3A8jD+iM=--bUOdoGR1pU8jmAhyyUYYDQ==

database:
  name: wBbk3izrSpueuO+B5sfwPBIdN3kaj/Xr8+/lsMDv14U=--X7tMxlYRzB65jFU7HTCwYA==
  host: kpIQUiCVWWBamfaO3skioA==--q92CJ3YlEnjrMdvVPlBjRQ==
  username: 2mVSzYh0Msk9M2dA31L79g==--uQlU+6JIeoKMcKCeKRozrw==
  password: rYjegfZw6RX8Q4FbdnSmqQ==--xvvqlnkgALX9/tS6pvAq9g==
  port: DPjJN/gJh0Yo5e2BRKUydw==--w48ooEld0JP6uMcSeBMgsA==

emailLogin:
  tables: VSuBlmssKWa60iKealVO4g==--K/TFbtkUZtPQ5Khj7sed0Q==
  passwordMinLength: QrYxbJxsFVSpKf4AoX3xAg==--UTfceQ5OJqsHPfJProWZ7g==
  rememberFor: XUffdrYqf26rbFDD3kbREA==--0h1spo62bQ5FLPQ4oHt+9Q==
  resetPasswordWithin: qTt8hBZ81uBrWbSHHkwCGw==--h4JOSQvLgcaBoaqYgHgc6Q==
  maximumRetries: FfSb0ERaz8bSP/G7SG0jug==--nztYnvg+lMdhz6AzGySb7A==
  unlockIn: vd7BZtwFk9qThTs6mRPhQw==--QGAOMiUMNgEvGyToQozeCA==
  passwordRegex: T7bQx2R8gm1lk7eMwR35W7nZWsnnBmGlz3ql91NjSXOB/8LbyvhhBi4EbugnQXtKEt5vnRvtpvC52Eu9Q4T/R33ZAaMG9w6Or4vDjleHgVY=--IRy+zvpJL3uez+Bv58qz7A==
  confirmationEmail: XjEDGO2sbLrgvxnTMNR3VQ==--FTXjzv78l0nCb2kQSDDZsA==


