
jwt:
  access_token_secret: eo6zaziJ0PDoC2n9fAH5jtlUeWnWasf6381S10DHgow=--0nZYzj4OF5wxs/OjyCQPLQ==
  refresh_token_secret: JLvhWbXH7yZl+XGoNlk9G6dEf4zc5LaeKUAPY9vVZ1g=--eqLFLkKb+tD8uE6AomIUPA==

swagger:
  username: /mdnjWQbrfqmmvdA7SHD/sx8mtsqZFabv/Ay59d6gJk=--u6yQy516kVbgRyfdSNgTtA==
  password: Xn6X2pkwDCtUDj/SMp/eGuiztmjI5igLjorH9rZeJJg=--OEO3QYnKwbHb24B9Q6n1Jg==

database:
  name: JmxN1qoLF+y83Ie13udwwUeQ1BN1SKhyVxxiwlZG0SI=--UerOxRWkx9HQeU4smDQKLw==
  host: tPMTD9GuE9W//Bx7LAMsYA==--f8yCq/pFdc4fAj++MRK6Kw==
  username: vGyD2Zj5n2fNoV8mTNQfJQ==--/i4HlFEjyN/ccjBkSZnl2Q==
  password: URFJxh6gQtzVPmLeRDr4Vg==--W54xUKLl3bhg8P+pJWnZKw==
  port: 5uv71Aa93O32zCLDjRg4WQ==--KQfe6vpAQps1+raT2nJqog==

emailLogin:
  tables: cwf+Yk9AxbR8zovKmmai5A==--5GcTGJQud/sUAGnnaRr8tQ==
  passwordMinLength: H7AxnJnLccxWjFPrTvxMIQ==--U9Sq50/xPyR2w6/23AaT+A==
  rememberFor: 4bF9OEcRuYwFK1vc2W13ZQ==--xnLsjv0boUc3yT3Iow7CcQ==
  resetPasswordWithin: FNK7roo2u2kC76yGNMU++w==--ABNs530er6Vo/z++wKWQ3A==
  maximumRetries: BvtMEREg+8GqZ9+4g/5ERQ==--p4/U0NpcEoxeZpvKA6lc4w==
  unlockIn: JKNX/nNYIe9drSGLvt3JGQ==--92ey20EOlsdBQrStDGt4GQ==
  passwordRegex: qxuxrANmwYmoTOSSp2bXJX+38gZLiXKoC/TTMltQsD540qLrlCfY6QkAIUjoayi/XmvgM31Xn0vOyp8jWGcIrQPobnaDMWcFi94IOYOT4sc=--acxM/9/+oN0zmLiyNBAYvg==
  confirmationEmail: fX4G6Prpv/27fCSMSb7qpw==--hlMDJyUir37G/waRP2IDYg==


