
jwt:
  access_token_secret: 41q6bAAKa+2lB6UfbW44S7l1Xzx1UfFdP9HpHIKoopA=--81iZH0urNxswcMluT9czLA==
  refresh_token_secret: Y7j3PnJN3ZTs67X9VrPFeCO2undrVrSr/ZJZEJX/KcM=--GKSH4sa/A9hswMerOJs5Lg==

swagger:
  username: jxZDen09Q4vXhortMq7tRcAqOZQuZCUVYfFqb9Y56es=--M8iujdu6eEB56IGFeoZyRg==
  password: yAPaqdawpJwGJdNgaJuTKUoIDqQvqz4vZSVuCuR0uxg=--q2Y/ZWt/wWii52arDuaN2g==

database:
  name: MOgdEiP0CGMCXunf0Nx97+kDb68LalIMxzfrHbrI76M=--yQNlhDTKwmJm/g+yUlqG7w==
  host: TU3UTGSpnPc2HoVpxC19eg==--EGPQDimu848qBsZkaa63BQ==
  username: CJwmQsvhnZpq6Sh6mm9hUA==--72xpQlwSV1Q1n+jsqHEytQ==
  password: k7Xco+W3LhOFt/hHz7CU7A==--vXgUU0FykrtVZTiE2QaW5A==
  port: jQyC/FImfeWd/Sy+wReknw==--urXJ2wkxm2rXNhyA8d5+uQ==

emailLogin:
  tables: mACv33KIpc+VPqsizVtfpQ==--uiQbSOIjLAYAkRUJySt/hA==
  passwordMinLength: K9zLI9gWm2xJglpm+hpGjA==--ZXL1/5qxyQaruH6cOt39hg==
  rememberFor: UZclifSidvtGm1rWULyPOw==--xqbZvEmVwG47o8mmeqJlag==
  resetPasswordWithin: tEcfsO7jQC8SIg8NeA18Kg==--CKVtyxj0urVo+Kp6G6RxmQ==
  maximumRetries: hBLobOmNzNhK/P7DzaLPTA==--ahiza5Du7y99gDOk+x7ncQ==
  unlockIn: XzWkvSOiX0+MjsdUVMPd4w==--2m5kdMXadgYVA93QahsDgg==
  passwordRegex: 3USQEouacFK+YwfY0tELzvJv48D5q4pr0pwfsRAWcat+VHDeog9q4FGQalT3QqnErXgNEZSUUOxe6Hu1HrAbj5mzE7uyLVKukTu6iD/6i7U=--fm64E/+EouTPBjNENMaOBg==
  confirmationEmail: P5EJdJZSX1RUJcxWgRIGuw==--l1/BdPUyCQtCouvtT1OsAw==


