
jwt:
  access_token_secret: p1V0zfy71gw8QmykSd20tmJM9xyVaAAMbccvmHneyJY=--v+mj9vjMVjsm7v10zThWSg==
  refresh_token_secret: KGZohef6fvNiul/5litIg2p32CLSjfScgnb9I0XKuyk=--WpP0mmrXo4QvqzgkDVSoog==

swagger:
  username: ZivDopahRZTTcHjNMkSWsbSnn7cBf8oSKSTwGaxpwv0=--78DC0dsnzwqhEhNS4trYTA==
  password: f7Z608vqml9nUJlgH/y2E0UhxGkFo8Ryw8M4XlMp2Nk=--WZ5mNOEZ9g2JnbPE1Wltaw==

database:
  name: 0uqm+SRSW4lQenB2E+81mgQ4FipJ9pxa/G58o9q9Sxc=--jgol6Tf98Ury4St5iW7lBA==
  host: JdV2mSO2pE3epi5q11EccA==--LFxu3RHdG/uBtu4qz8jBbA==
  username: ZUMwVfoOeL25hQmLSAeE/Q==--4UYDP5Gagzc0rY4yF8t2iQ==
  password: 2gv94BWifpMD2Sxs+Ib7dQ==--HxxZRHctYBqxIA4E5GAJHQ==
  port: H4rcyZmlD8dZ3LJ5AsqFkw==--J3fOwE+cV6V2Up/WK5d0yg==

emailLogin:
  tables: 45edHwmXYBgXF9qxw6IwFQ==--5P7KkTtej+CAYS0FprH/mg==
  passwordMinLength: fD/FP1L2J9w5FlhNkFsO6g==--8tn335zjF9BOaKQCu1b80Q==
  rememberFor: 4WvhoGJ3YEdqnGVadXC8wA==--OdYvUu+HYe7ZtuSVs4hoBA==
  resetPasswordWithin: j0uMUuZMziIUqmJJQGohgA==--2KnLwGv16VVp8tHJYlXlbA==
  maximumRetries: rxukDV9Ri2KjAUEEDnrmVQ==--MV1sG0t8t1I/u3oyoDCH+w==
  unlockIn: R7pet+rQFASRuuK7Cwzzlg==--9tJAuhnNg9BR7PZM3tEz3Q==
  passwordRegex: JwC/0uWEc+THCI31uqFty/Eq8zB5/b4pX7Sh+9IF1xMu3UQvVwbBbe0G9C1j7eo/Pl6FB7teLhZoVjY57uN2lu324o2+21czfsjkSlrbkqM=--8HW6xkHSJl2YEKbwWa04eg==
  confirmationEmail: Mcel+Gsoh0/WlDGnElZUZA==--IwsJHb0NLQjWJ9lPAWptuw==


