
jwt:
  access_token_secret: 0Luc4kwWBDdolWtHN58Q1CNmyT4WhrKVp07ZGtyICB4=--Cjh9IARMJJ7YFdwubP+nYg==
  refresh_token_secret: zjnNE+SXE36XdFogHTkCLPhtWh1Q8jEKq2DnASRWIwo=--6ona3hIR4yxtMfpSpB8zLw==

swagger:
  username: RNmn2jf5fO5xaQTP/KdBmNgHC39XBP5IF/oywwe2Zv0=--DMd4ZmFBeqtlHzKjIyTjqw==
  password: b0arXEhg8lmOUAMepURsiURy8eBTYOygwS3Z1ZwQfB0=--WoArCMplEENmtIZTM2SgFg==

database:
  name: jUUPEe1SRM2OLsFSxLhw7831/psquP7zc9VnREZbH2c=--OlIC+/9owM5n6fBLP1anIA==
  host: rfQCeleG0rMg0s+4dtTp+A==--bMDthmDvaTwcGy8VvY2B7Q==
  username: n38DB8HmgHl7Y4y5lSTPJw==--VoUJbrZzqwyn7M3JaDjCAg==
  password: d0IkHEp8Fv+LBHm4e8wU9g==--iut13okKpbsqPGGRdYS5qg==
  port: p19f4nNgbF3za/F6d3lx7g==--c/OQT24T9qXhU7yUTR9ofA==

emailLogin:
  tables: pfGJ3qn7aLChObjmV2+DkA==--teNpm3VYg81A0jFkXmh3PA==
  passwordMinLength: GYWlMic5f35cS0RqAyxv3Q==--6lbJfpYtpx5u+gDzk/PHhQ==
  rememberFor: UDp1NG7QwIDEs4nwiudFLQ==--B/eX4udqdTkGUZFqgmqoug==
  resetPasswordWithin: Wu+cttf5e+zLMuFSHuNvPA==--8ooG3TNpSw9Qn0GR9Fa0UA==
  maximumRetries: +PHQN4l5kmQ+W7rfePdrdA==--G6lxTvxoCzyuk3Oj2YofrQ==
  unlockIn: hyIkV7s5upIKY8B7fz+jPw==--liK/SvKtb8QXZEbHVkdTbQ==
  passwordRegex: cMpz079dUfiTJ9quTvRjbjL9PJA+vDBY/3AOq2T9yAyTKHV8DpqM3f0U36qs2HI0VhZLu1WOrO6y09lu9x7UWNhSHorFbT6zHyD2dgSguI4=--jujfE+NbIzmqnCTEDGMr/A==
  confirmationEmail: y6QlbnWG9NUG3ao4VsbC5w==--z00kgvSLaY1m8ICGMqJDnw==


