
jwt:
  access_token_secret: 6JggdnuKaCv/SH93BF9pFn2rnp/yeuQA7fSgEUIgU50=--QC7Qxx+Eb30BqYNV7YJAqA==
  refresh_token_secret: r4Bu83/wjCcvJpXuVNUWWETDxIuLm1Op4IgL8558RJU=--LfJZRQGOLcJfRB33tG5/Lw==

swagger:
  username: sbymrNruQL0sidHtPlHlcsXtmcXGTkuiChVT6UOlmEY=--kap8yIxHROTeIHGO+XU8Tg==
  password: A5kfPxJAqYwYiQ9WDASu5bSyf7TQY2I70N4YiVtZSvI=--g/ZKVSlSF5WWOCR5+sacDw==

database:
  name: EGBsmTsbEkWDC95mflw+MfhHn+5FgnMEDqBTBatNhCM=--8iOfp9AntbPw2XcuL5lAVw==
  host: vJ6JTypSiSOwCiG3hghT1w==--R22gnGoCFTXMXzrKEXkRXw==
  username: muFdmMJNih3RZJKmGRbd+g==--H6ZKuh0c31oliXkPpo6OkA==
  password: eYBlTj+aXaAeHQuGBa4bRQ==--eP4vxhrVJw1CHYPZzyB3GQ==
  port: SUZMX3SqbpgTjIubp8or6A==--Esnn6O1pCAWL+N0j1O9opg==

emailLogin:
  tables: H9EYGSN08KgoqLceusaJpQ==--wMglSry8XoD0wUQ8VccJgQ==
  passwordMinLength: G4r+XEeJBBDzJn2RJe3uUA==--TOamfw7RJah4ZeYyClqW6A==
  rememberFor: zRZPXFNefoawvtkib6EVZA==--O2RpMkvJup8RLUiZ1o8KDA==
  resetPasswordWithin: 0/0RfTr1yEB6OBS+nERAWw==--i4g+fwnGIDMvdvperhC4iA==
  maximumRetries: WS9n0KZ6linKOybKishRTQ==--YYIRo6nZcQUMxDNAqBpFuw==
  unlockIn: Z/U7qaTsDc/QLzC1/cIa3A==--Fy2g3v8gxXefPgnUKhjf2Q==
  passwordRegex: 3+hgefFZyfFGgpvr3m3gOKV41/mXfXwD2T3n0yRI5f6KRZzj3Y4PAnUPmO6kvjgTdRRtkwkAGvFNllDJbFtBj38t8QLf5xyFMjlly/rJ8uk=--mKc9wYT0ZFoWIfcLtrtBEA==
  confirmationEmail: OD8ekyiCZ4TzAO1jb/81DQ==--VX2XC4b5IoqiW0+nWOIfGg==


